'use strict';

/* Castle Combo photo recognizer v6
   Core idea: do NOT assume a 3x3 grid first.
   1) Find many 64:90-ish quadrilateral candidates.
   2) Perspective-warp each candidate to the exact common card layout (320x450).
   3) Use fixed ROIs (cost/shield/name/art/effect/score) to shortlist cards.
   4) Verify the shortlist with ORB feature matches + RANSAC homography on the illustration.
   5) Reject rectangle candidates that do not geometrically match any of the 90 scanned cards.
   6) OCR the fixed card-name strip only for the final 9 cards and use it as a tie-breaker.
   7) Determine 3x3 position only after 9 physical cards have been identified.
*/

const photoState={cvReady:false,features:null,img:null,objectUrl:null,detections:[],detectedItems:[],manualPoints:[],manualMode:false,ocrWorker:null};
const $p=s=>document.querySelector(s),photoInput=$p('#photoInput'),photoImg=$p('#photoSource'),photoCanvas=$p('#photoCanvas'),photoCtx=photoCanvas.getContext('2d'),analyzeBtn=$p('#analyzePhotoBtn'),manualBtn=$p('#manualModeBtn'),applyBtn=$p('#applyRecognizedBtn'),photoStatus=$p('#photoStatus'),recognitionResults=$p('#recognitionResults');
function setPhotoStatus(msg,kind=''){photoStatus.textContent=msg;photoStatus.className=`photo-status ${kind}`.trim();}
function onOpenCvReady(){const ready=()=>{photoState.cvReady=true;setPhotoStatus(photoState.features?'사진을 선택하면 자동 분석할 수 있습니다.':'카드 인식 데이터를 불러오는 중…');analyzeBtn.disabled=!photoState.img||!photoState.features;};if(typeof cv==='object'&&cv&&typeof cv.then==='function')cv.then(ready);else ready();}window.onOpenCvReady=onOpenCvReady;
async function loadFeatures(){try{const r=await fetch('data/card-recognition-v6.json?v=20260809-6');if(!r.ok)throw new Error(`HTTP ${r.status}`);photoState.features=await r.json();setPhotoStatus(photoState.cvReady?'v6 카드 90장 인식 데이터 준비 완료.':'OpenCV를 불러오는 중…','ok');analyzeBtn.disabled=!photoState.cvReady||!photoState.img;}catch(e){console.error(e);setPhotoStatus('data/card-recognition-v6.json을 불러오지 못했습니다.','error');}}
function fitCanvasToImage(img){const maxW=1800,scale=Math.min(1,maxW/img.naturalWidth);photoCanvas.width=Math.round(img.naturalWidth*scale);photoCanvas.height=Math.round(img.naturalHeight*scale);photoCanvas.dataset.scale=String(scale);photoCtx.drawImage(img,0,0,photoCanvas.width,photoCanvas.height);}
photoInput.addEventListener('change',()=>{const f=photoInput.files?.[0];if(!f)return;if(photoState.objectUrl)URL.revokeObjectURL(photoState.objectUrl);photoState.objectUrl=URL.createObjectURL(f);photoImg.onload=()=>{photoState.img=photoImg;fitCanvasToImage(photoImg);photoState.detections=[];photoState.detectedItems=[];photoState.manualPoints=[];photoState.manualMode=false;manualBtn.classList.remove('active');recognitionResults.innerHTML='';applyBtn.hidden=true;analyzeBtn.disabled=!photoState.cvReady||!photoState.features;setPhotoStatus(photoState.cvReady?'사진 준비 완료. “자동 분석”을 눌러주세요.':'사진 준비 완료. OpenCV를 불러오는 중…');};photoImg.src=photoState.objectUrl;});

const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),centerOf=p=>({x:p.reduce((s,v)=>s+v.x,0)/p.length,y:p.reduce((s,v)=>s+v.y,0)/p.length});
function boundsOf(p){const xs=p.map(v=>v.x),ys=p.map(v=>v.y),x=Math.min(...xs),y=Math.min(...ys),x2=Math.max(...xs),y2=Math.max(...ys);return{x,y,width:x2-x,height:y2-y};}
function boxIoU(a,b){const x1=Math.max(a.x,b.x),y1=Math.max(a.y,b.y),x2=Math.min(a.x+a.width,b.x+b.width),y2=Math.min(a.y+a.height,b.y+b.height),inter=Math.max(0,x2-x1)*Math.max(0,y2-y1),u=a.width*a.height+b.width*b.height-inter;return u?inter/u:0;}
function orderQuad(p){const tl=p.reduce((a,b)=>(a.x+a.y)<(b.x+b.y)?a:b),br=p.reduce((a,b)=>(a.x+a.y)>(b.x+b.y)?a:b),tr=p.reduce((a,b)=>(a.y-a.x)<(b.y-b.x)?a:b),bl=p.reduce((a,b)=>(a.y-a.x)>(b.y-b.x)?a:b);return[tl,tr,br,bl];}
function portraitQuad(points){let q=orderQuad(points);const w=(dist(q[0],q[1])+dist(q[3],q[2]))/2,h=(dist(q[0],q[3])+dist(q[1],q[2]))/2;if(w>h)q=[q[1],q[2],q[3],q[0]];return q;}
function contourApproxQuad(cnt,eps){const peri=cv.arcLength(cnt,true),a=new cv.Mat();try{cv.approxPolyDP(cnt,a,eps*peri,true);if(a.rows!==4||!cv.isContourConvex(a))return null;const p=[];for(let i=0;i<4;i++)p.push({x:a.data32S[i*2],y:a.data32S[i*2+1]});return p;}finally{a.delete();}}
function minRectQuad(cnt){return cv.RotatedRect.points(cv.minAreaRect(cnt)).map(p=>({x:p.x,y:p.y}));}
function contourToCard(cnt,imgArea){const area=Math.abs(cv.contourArea(cnt));if(area<imgArea*.003||area>imgArea*.24)return null;let pts=null;for(const e of [.012,.018,.025,.035,.05]){pts=contourApproxQuad(cnt,e);if(pts)break;}if(!pts)pts=minRectQuad(cnt);const q=portraitQuad(pts),w=(dist(q[0],q[1])+dist(q[3],q[2]))/2,h=(dist(q[0],q[3])+dist(q[1],q[2]))/2;if(w<34||h<50)return null;const ratio=w/h,expected=64/90;if(ratio<.48||ratio>.90)return null;const b=boundsOf(q),rect=area/Math.max(1,b.width*b.height);if(rect<.34)return null;const ratioFit=Math.exp(-Math.pow((ratio-expected)/.12,2)),c=centerOf(q);return{...b,quad:q,center:c,area,ratio,shapeScore:ratioFit*(.5+.5*Math.min(1,rect+.15))};}
function collect(binary,src,out){const cs=new cv.MatVector(),h=new cv.Mat();try{cv.findContours(binary,cs,h,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE);const A=src.cols*src.rows;for(let i=0;i<cs.size();i++){const c=cs.get(i);try{const q=contourToCard(c,A);if(q)out.push(q);}finally{c.delete();}}}finally{cs.delete();h.delete();}}
function detectCardCandidates(src){const gray=new cv.Mat(),lab=new cv.Mat(),channels=new cv.MatVector(),blur=new cv.Mat(),edge=new cv.Mat(),morph=new cv.Mat(),adaptive=new cv.Mat(),k3=cv.Mat.ones(3,3,cv.CV_8U),k5=cv.Mat.ones(5,5,cv.CV_8U),cand=[];try{cv.cvtColor(src,gray,cv.COLOR_RGBA2GRAY);cv.GaussianBlur(gray,blur,new cv.Size(5,5),0);for(const [lo,hi] of [[18,55],[28,90],[45,135],[70,210]]){cv.Canny(blur,edge,lo,hi);cv.morphologyEx(edge,morph,cv.MORPH_CLOSE,k5);collect(morph,src,cand);}cv.adaptiveThreshold(gray,adaptive,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,cv.THRESH_BINARY_INV,35,7);cv.morphologyEx(adaptive,morph,cv.MORPH_CLOSE,k3);collect(morph,src,cand);
    // Add edge candidates from L channel to survive colored/dark tabletops.
    cv.cvtColor(src,lab,cv.COLOR_RGBA2RGB);cv.cvtColor(lab,lab,cv.COLOR_RGB2Lab);cv.split(lab,channels);const L=channels.get(0);cv.Canny(L,edge,25,100);cv.morphologyEx(edge,morph,cv.MORPH_CLOSE,k5);collect(morph,src,cand);L.delete();
    cand.sort((a,b)=>(b.area*b.shapeScore)-(a.area*a.shapeScore));const picked=[];for(const q of cand){if(picked.some(p=>boxIoU(p,q)>.55||dist(p.center,q.center)<Math.min(p.height,q.height)*.18))continue;picked.push(q);if(picked.length>=28)break;}return picked;
  }finally{gray.delete();lab.delete();channels.delete();blur.delete();edge.delete();morph.delete();adaptive.delete();k3.delete();k5.delete();}}
function warpCard(src,item){const q=portraitQuad(item.quad),[W,H]=photoState.features.normalizedSize||[320,450],sp=cv.matFromArray(4,1,cv.CV_32FC2,[q[0].x,q[0].y,q[1].x,q[1].y,q[2].x,q[2].y,q[3].x,q[3].y]),dp=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,W-1,0,W-1,H-1,0,H-1]),M=cv.getPerspectiveTransform(sp,dp),out=new cv.Mat();try{cv.warpPerspective(src,out,M,new cv.Size(W,H),cv.INTER_CUBIC,cv.BORDER_REPLICATE);return out;}finally{sp.delete();dp.delete();M.delete();}}
function cropCentered(src,item){const[W,H]=photoState.features.normalizedSize||[320,450],x=Math.max(0,Math.round(item.x)),y=Math.max(0,Math.round(item.y)),x2=Math.min(src.cols,Math.round(item.x+item.width)),y2=Math.min(src.rows,Math.round(item.y+item.height)),roi=src.roi(new cv.Rect(x,y,Math.max(1,x2-x),Math.max(1,y2-y))),out=new cv.Mat();try{cv.resize(roi,out,new cv.Size(W,H),0,0,cv.INTER_AREA);return out;}finally{roi.delete();}}
function cardMatFor(src,item){return item.quad?warpCard(src,item):cropCentered(src,item);}
function roiClone(src,r){const[rx,ry,rw,rh]=r,W=src.cols,H=src.rows,x=Math.max(0,Math.round(rx*W)),y=Math.max(0,Math.round(ry*H)),w=Math.max(1,Math.min(W-x,Math.round(rw*W))),h=Math.max(1,Math.min(H-y,Math.round(rh*H))),roi=src.roi(new cv.Rect(x,y,w,h)),o=roi.clone();roi.delete();return o;}

function b64Bytes(s){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a;}
function ensureDecoded(){if(photoState.features._decoded)return;for(const c of photoState.features.cards){c._regions={};for(const[k,v]of Object.entries(c.regions))c._regions[k]=b64Bytes(v);c._orbArtDes=b64Bytes(c.orbArt.des||'');c._orbFullDes=b64Bytes(c.orbFull.des||'');}photoState.features._decoded=true;}
function regionSignature(card,r){const roi=roiClone(card,r),g=new cv.Mat(),eq=new cv.Mat(),gx=new cv.Mat(),gy=new cv.Mat(),mag=new cv.Mat(),norm=new cv.Mat(),sm=new cv.Mat(),sz=photoState.features.signatureSize||24;try{cv.cvtColor(roi,g,cv.COLOR_RGBA2GRAY);cv.equalizeHist(g,eq);cv.Sobel(eq,gx,cv.CV_32F,1,0,3);cv.Sobel(eq,gy,cv.CV_32F,0,1,3);cv.magnitude(gx,gy,mag);cv.normalize(mag,norm,0,255,cv.NORM_MINMAX,cv.CV_8U);cv.resize(norm,sm,new cv.Size(sz,sz),0,0,cv.INTER_AREA);return new Uint8Array(sm.data);}finally{roi.delete();g.delete();eq.delete();gx.delete();gy.delete();mag.delete();norm.delete();sm.delete();}}
function corr(a,b){if(!a||!b||a.length!==b.length)return 0;let ma=0,mb=0;for(let i=0;i<a.length;i++){ma+=a[i];mb+=b[i];}ma/=a.length;mb/=b.length;let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y;}const den=Math.sqrt(da*db);return den?Math.max(0,n/den):0;}
function querySigs(card){const o={};for(const[k,r]of Object.entries(photoState.features.regions))o[k]=regionSignature(card,r);return o;}
function sigShortlist(card,limit=15){ensureDecoded();const q=querySigs(card),w={art:.42,cost:.16,shield:.18,name:.10,effect:.07,score:.07},arr=[];for(const c of photoState.features.cards){let s=0;const parts={};for(const[k,v]of Object.entries(w)){parts[k]=corr(q[k],c._regions[k]);s+=v*parts[k];}arr.push({item:c,sig:s,...parts});}arr.sort((a,b)=>b.sig-a.sig);return arr.slice(0,limit);}

function orbQuery(card,regionName='art'){const roi=regionName==='full'?card.clone():roiClone(card,photoState.features.regions[regionName]),gray=new cv.Mat(),clahe=new cv.CLAHE(2.0,new cv.Size(8,8)),eq=new cv.Mat(),kp=new cv.KeyPointVector(),des=new cv.Mat(),orb=new cv.ORB(900);try{cv.cvtColor(roi,gray,cv.COLOR_RGBA2GRAY);clahe.apply(gray,eq);const mask=new cv.Mat();try{orb.detectAndCompute(eq,mask,kp,des);}finally{mask.delete();}const pts=[];for(let i=0;i<kp.size();i++){const k=kp.get(i);pts.push([k.pt.x/eq.cols,k.pt.y/eq.rows]);}return{pts,des:des.clone(),w:eq.cols,h:eq.rows};}finally{roi.delete();gray.delete();eq.delete();kp.delete();orb.delete();clahe.delete();des.delete();}}
function templateMat(bytes,count){const m=new cv.Mat(count,32,cv.CV_8U);if(bytes.length)m.data.set(bytes);return m;}
function orbMatch(query,tpl){if(!query?.des||query.des.rows<4||!tpl?.count||tpl.count<4)return{good:0,inliers:0,geom:0};const td=templateMat(tpl._bytes||b64Bytes(tpl.des),tpl.count),matcher=new cv.BFMatcher(cv.NORM_HAMMING,false),vv=new cv.DMatchVectorVector();try{matcher.knnMatch(query.des,td,vv,2);const good=[];for(let i=0;i<vv.size();i++){const v=vv.get(i);if(v.size()>=2){const m=v.get(0),n=v.get(1);if(m.distance<.76*n.distance)good.push([m.queryIdx,m.trainIdx]);}v.delete();}let inliers=0;if(good.length>=4){try{const src=[],dst=[];for(const[qi,ti]of good){src.push(query.pts[qi][0],query.pts[qi][1]);dst.push(tpl.kp[ti][0],tpl.kp[ti][1]);}const sm=cv.matFromArray(good.length,1,cv.CV_32FC2,src),dm=cv.matFromArray(good.length,1,cv.CV_32FC2,dst),mask=new cv.Mat();try{cv.findHomography(sm,dm,cv.RANSAC,.035,mask);if(mask.rows)for(let i=0;i<mask.rows;i++)if(mask.data[i])inliers++;}finally{sm.delete();dm.delete();mask.delete();}}catch(e){inliers=good.length;}}
      const geom=(1-Math.exp(-inliers/14))*.82+(1-Math.exp(-good.length/25))*.18;return{good:good.length,inliers,geom};
  }finally{td.delete();matcher.delete();vv.delete();}}
function fastRecognizeOrientation(card){const shortlist=sigShortlist(card,15),qArt=orbQuery(card,'art'),qFull=orbQuery(card,'full');try{for(const c of shortlist){c.item.orbArt._bytes=c.item._orbArtDes;c.item.orbFull._bytes=c.item._orbFullDes;const a=orbMatch(qArt,c.item.orbArt),f=a.inliers>=8?{good:0,inliers:0,geom:0}:orbMatch(qFull,c.item.orbFull);c.orbGood=Math.max(a.good,f.good);c.inliers=Math.max(a.inliers,f.inliers);c.geom=Math.max(a.geom,f.geom);c.hybrid=.68*c.geom+.32*c.sig;}shortlist.sort((a,b)=>b.hybrid-a.hybrid);return shortlist;}finally{qArt.des.delete();qFull.des.delete();}}
function rotate180(src){const o=new cv.Mat();cv.rotate(src,o,cv.ROTATE_180);return o;}
function fastRecognize(card){const a=fastRecognizeOrientation(card),r=rotate180(card);try{const b=fastRecognizeOrientation(r);return (b[0]?.hybrid||0)>(a[0]?.hybrid||0)+.025?{top:b,rot180:true}:{top:a,rot180:false};}finally{r.delete();}}

function normalizeText(s){return(s||'').replace(/[^가-힣0-9]/g,'');}
function lev(a,b){a=normalizeText(a);b=normalizeText(b);if(!a||!b)return Math.max(a.length,b.length);const d=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let p=d[0];d[0]=i;for(let j=1;j<=b.length;j++){const t=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,p+(a[i-1]===b[j-1]?0:1));p=t;}}return d[b.length];}
function textSim(a,b){a=normalizeText(a);b=normalizeText(b);return a&&b?Math.max(0,1-lev(a,b)/Math.max(a.length,b.length)):0;}
function matCanvas(m){const c=document.createElement('canvas');c.width=m.cols;c.height=m.rows;cv.imshow(c,m);return c;}
function nameOcrMat(card){const r=photoState.features.regions.name,strip=roiClone(card,r),rot=new cv.Mat(),g=new cv.Mat(),clahe=new cv.CLAHE(2.5,new cv.Size(8,8)),eq=new cv.Mat(),bin=new cv.Mat(),scaled=new cv.Mat();try{cv.rotate(strip,rot,cv.ROTATE_90_CLOCKWISE);cv.cvtColor(rot,g,cv.COLOR_RGBA2GRAY);clahe.apply(g,eq);cv.adaptiveThreshold(eq,bin,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,cv.THRESH_BINARY,31,9);cv.resize(bin,scaled,new cv.Size(bin.cols*4,bin.rows*4),0,0,cv.INTER_CUBIC);return scaled.clone();}finally{strip.delete();rot.delete();g.delete();eq.delete();bin.delete();scaled.delete();clahe.delete();}}
async function ensureOcr(){if(photoState.ocrWorker)return photoState.ocrWorker;if(typeof Tesseract==='undefined')throw new Error('Tesseract.js를 불러오지 못했습니다.');photoState.ocrWorker=await Tesseract.createWorker(['kor'],1,{logger:m=>{if(m.progress)setPhotoStatus(`한글 카드명 OCR ${Math.round(m.progress*100)}%`,'working');}});return photoState.ocrWorker;}
async function ocrName(card){try{const w=await ensureOcr(),m=nameOcrMat(card),c=matCanvas(m);m.delete();await w.setParameters({tessedit_pageseg_mode:Tesseract.PSM.SINGLE_LINE,preserve_interword_spaces:'0'});const{data}=await w.recognize(c);return normalizeText(data.text);}catch(e){console.warn(e);return'';}}
async function finalRecognize(card,fast){let chosen=card,r=null;if(fast.rot180){r=rotate180(card);chosen=r;}try{const txt=await ocrName(chosen),top=fast.top.map(c=>({...c,textScore:textSim(txt,c.item.ko)}));for(const c of top)c.final=c.hybrid+(txt?.length>=2?.28*c.textScore:0)+(c.textScore>=.82?.08:0);top.sort((a,b)=>b.final-a.final);const a=top[0]?.final||0,b=top[1]?.final||0,margin=a-b,conf=Math.max(1,Math.min(99,Math.round(30+margin*180+(top[0]?.inliers||0)*1.15)));return{top,ocrText:txt,confidence:conf,needsReview:(top[0]?.inliers||0)<7||margin<.06};}finally{if(r)r.delete();}}

async function validateCandidates(src,candidates){const scored=[];for(let i=0;i<candidates.length;i++){setPhotoStatus(`카드 테두리 후보 검증 중… ${i+1}/${candidates.length}`,'working');const m=warpCard(src,candidates[i]);try{const f=fastRecognize(m),best=f.top[0],second=f.top[1],margin=(best?.hybrid||0)-(second?.hybrid||0);scored.push({...candidates[i],fast:f,recognitionScore:(best?.hybrid||0)+Math.min(.35,(best?.inliers||0)/80)+Math.max(0,margin)*.4,bestInliers:best?.inliers||0});}finally{m.delete();}await new Promise(r=>setTimeout(r,0));}
  scored.sort((a,b)=>b.recognitionScore-a.recognitionScore);const picked=[];for(const q of scored){if(q.bestInliers<4&&picked.length>=9)continue;if(picked.some(p=>boxIoU(p,q)>.30||dist(p.center,q.center)<Math.min(p.height,q.height)*.30))continue;picked.push(q);if(picked.length===9)break;}return picked;}
function sortGrid(items){if(items.length!==9)return items;const sorted=[...items].sort((a,b)=>a.center.y-b.center.y),rows=[sorted.slice(0,3),sorted.slice(3,6),sorted.slice(6,9)];rows.forEach(r=>r.sort((a,b)=>a.center.x-b.center.x));return rows.flat();}
function overlay(items){fitCanvasToImage(photoState.img);photoCtx.save();photoCtx.lineWidth=4;photoCtx.font='bold 18px system-ui';items.forEach((it,i)=>{photoCtx.strokeStyle='#22c55e';photoCtx.fillStyle='rgba(20,20,20,.76)';const q=portraitQuad(it.quad);photoCtx.beginPath();photoCtx.moveTo(q[0].x,q[0].y);q.slice(1).forEach(p=>photoCtx.lineTo(p.x,p.y));photoCtx.closePath();photoCtx.stroke();const c=it.center;photoCtx.fillRect(c.x-18,c.y-14,36,28);photoCtx.fillStyle='#fff';photoCtx.fillText(String(i+1),c.x-5,c.y+7);});photoCtx.restore();}
function makeUnique(results){const ord=results.map((r,i)=>({i,m:(r.top[0]?.final||r.top[0]?.hybrid||0)-(r.top[1]?.final||r.top[1]?.hybrid||0)})).sort((a,b)=>b.m-a.m),used=new Set();for(const o of ord){const r=results[o.i],ch=r.top.find(c=>!used.has(c.item.id))||r.top[0];if(ch){r.top=[ch,...r.top.filter(c=>c.item.id!==ch.item.id)];used.add(ch.item.id);}}return results;}
function candidateButton(c,slot){const used=new Set(photoState.detections.map((r,i)=>i===slot?null:r.top[0]?.item.id).filter(Boolean)),dis=used.has(c.item.id);return`<button type="button" class="candidate" data-slot="${slot}" data-id="${c.item.id}" ${dis?'disabled':''}><b>${c.item.ko}</b><small>기하일치 ${c.inliers||0} · 그림 ${Math.round((c.art||0)*100)} · 비용 ${Math.round((c.cost||0)*100)} · 방패 ${Math.round((c.shield||0)*100)} · OCR ${Math.round((c.textScore||0)*100)}%${dis?' · 다른 칸에서 선택됨':''}</small></button>`;}
function renderRecognition(results){recognitionResults.innerHTML=results.map((r,i)=>`<article class="recognition-card ${r.needsReview?'review':''}"><div class="recognition-head"><span>${Math.floor(i/3)+1}행 ${i%3+1}열</span><strong>${r.needsReview?'확인 필요':'자동 인식'}</strong></div><h3>${r.top[0]?.item.ko||'인식 실패'}</h3><div class="confidence"><i style="width:${r.confidence}%"></i></div><small>신뢰도 ${r.confidence}% · OCR: ${r.ocrText||'읽지 못함'} · RANSAC 일치점 ${r.top[0]?.inliers||0}</small><details ${r.needsReview?'open':''}><summary>후보 확인/변경</summary>${r.top.slice(0,5).map(c=>candidateButton(c,i)).join('')}</details></article>`).join('');recognitionResults.querySelectorAll('.candidate:not([disabled])').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.slot,r=photoState.detections[i],c=r.top.find(x=>x.item.id===b.dataset.id);if(!c)return;r.top=[c,...r.top.filter(x=>x.item.id!==c.item.id)];r.needsReview=false;r.confidence=Math.max(r.confidence,82);makeUnique(photoState.detections);renderRecognition(photoState.detections);}));applyBtn.hidden=false;}
async function recognizeNine(src,items){const results=[];for(let i=0;i<items.length;i++){setPhotoStatus(`${i+1}/9 카드 최종 분석 중… 카드명·비용·방패·일러스트 교차검증`,'working');const m=warpCard(src,items[i]);try{results.push(await finalRecognize(m,items[i].fast||fastRecognize(m)));}finally{m.delete();}await new Promise(r=>setTimeout(r,0));}photoState.detections=makeUnique(results);renderRecognition(photoState.detections);const n=results.filter(r=>r.needsReview).length;setPhotoStatus(n?`9장 인식 완료. ${n}장은 후보를 확인해주세요.`:'9장 인식 완료. 결과를 확인하고 배열에 적용하세요.',n?'warn':'ok');}

analyzeBtn.addEventListener('click',async()=>{if(!photoState.cvReady||!photoState.features||!photoState.img)return;analyzeBtn.disabled=true;applyBtn.hidden=true;recognitionResults.innerHTML='';const src=cv.imread(photoCanvas);try{setPhotoStatus('64×90 카드 테두리 후보를 넉넉하게 찾는 중…','working');let cand=detectCardCandidates(src);if(cand.length<9){overlay(cand);setPhotoStatus(`카드 후보를 ${cand.length}개만 찾았습니다. 촬영 간격/반사를 확인하거나 수동 4점 지정을 사용해주세요.`,'warn');return;}cand=await validateCandidates(src,cand);if(cand.length!==9){overlay(cand);setPhotoStatus(`기준 카드와 실제로 일치하는 테두리를 ${cand.length}개 찾았습니다. 9장이 아니면 수동 지정을 사용해주세요.`,'warn');return;}cand=sortGrid(cand);photoState.detectedItems=cand;overlay(cand);await recognizeNine(src,cand);}catch(e){console.error(e);setPhotoStatus(`분석 중 오류: ${e.message}`,'error');}finally{src.delete();analyzeBtn.disabled=false;}});

manualBtn.addEventListener('click',()=>{if(!photoState.img)return;photoState.manualMode=true;photoState.manualPoints=[];manualBtn.classList.add('active');fitCanvasToImage(photoState.img);setPhotoStatus('수동 지정: 왼쪽 위 → 오른쪽 위 → 오른쪽 아래 → 왼쪽 아래 카드의 중심을 차례로 눌러주세요.','warn');});
photoCanvas.addEventListener('click',async e=>{if(!photoState.manualMode||!photoState.img)return;const r=photoCanvas.getBoundingClientRect(),x=(e.clientX-r.left)*photoCanvas.width/r.width,y=(e.clientY-r.top)*photoCanvas.height/r.height;photoState.manualPoints.push({x,y});photoCtx.fillStyle='#ef4444';photoCtx.beginPath();photoCtx.arc(x,y,8,0,Math.PI*2);photoCtx.fill();if(photoState.manualPoints.length<4){setPhotoStatus(`수동 지정 ${photoState.manualPoints.length}/4 완료.`,'warn');return;}photoState.manualMode=false;manualBtn.classList.remove('active');const[tl,tr,br,bl]=photoState.manualPoints,lerp=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}),centers=[];for(let rr=0;rr<3;rr++){const l=lerp(tl,bl,rr/2),ri=lerp(tr,br,rr/2);for(let cc=0;cc<3;cc++)centers.push(lerp(l,ri,cc/2));}const hs=(dist(tr,tl)+dist(br,bl))/4,vs=(dist(bl,tl)+dist(br,tr))/4,w=hs*.68,h=vs*.88,items=centers.map(c=>({x:c.x-w/2,y:c.y-h/2,width:w,height:h,center:c,quad:[{x:c.x-w/2,y:c.y-h/2},{x:c.x+w/2,y:c.y-h/2},{x:c.x+w/2,y:c.y+h/2},{x:c.x-w/2,y:c.y+h/2}]}));const src=cv.imread(photoCanvas);try{for(const it of items){const m=warpCard(src,it);try{it.fast=fastRecognize(m);}finally{m.delete();}}overlay(items);await recognizeNine(src,items);}catch(err){console.error(err);setPhotoStatus(`인식 오류: ${err.message}`,'error');}finally{src.delete();}});
applyBtn.addEventListener('click',()=>{if(photoState.detections.length!==9)return;const ids=photoState.detections.map(r=>r.top[0]?.item.id).filter(Boolean);if(new Set(ids).size!==ids.length){setPhotoStatus('같은 카드가 두 칸 이상 선택되어 있습니다. 후보를 수정해주세요.','error');return;}photoState.detections.forEach((r,i)=>{state.slots[i]={cardId:r.top[0].item.id,faceDown:false,purse:0,lockUnused:true};});save();render();setPhotoStatus('인식한 9장을 배열에 적용했습니다.','ok');$p('.tableau-section').scrollIntoView({behavior:'smooth',block:'start'});});
loadFeatures();
